### ISSUE TITLE
DB container not starting with current docker-compose.example.yml file

### ISSUE THREAD

**Issue by jelkose** [standardnotes/server#1055]
After updating my local environment, the db-container did not start anymore. 
The following error is displayed: 
`[Server] unknown variable 'default-authentication-plugin=mysql_native_password'.`
The update pulled the newest version of `mysql:8` (which stands in docker-compose.example.yml) from docker, which currently is 8.4. In this version the native password plugin was removed (see https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html).

A workaround is to replace the `--default-authentication-plugin=mysql_native_password` flag in https://github.com/standardnotes/server/blob/dbb0e4a9746c022126e719ddbcd31cec9fca12aa/docker-compose.example.yml#L42 by `--mysql-native-password=ON` which enables the native password plugin again (see https://dev.mysql.com/doc/refman/8.4/en/native-pluggable-authentication.html).
But as this plugin is deprecated and will be removed completely in future releases, I think using a more up-to-date authentication plugin would be better.

Cheers,
Jelko

**Comment by tuxnet** [comment]
I have already created a pull request #1054 which solves the problem until another plugin is implemented

**Comment by ChesterHCopperpot** [comment]
If I make this change, my SN no longer starts:

```
user@VPN:~/standardnotes$ sudo docker-compose up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting server_self_hosted ... 
Recreating db_self_hosted   ... 
Starting server_self_hosted     ... done
Starting localstack_self_hosted ... 
Starting cache_self_hosted      ... done
Starting localstack_self_hosted ... done

ERROR: for db  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 192, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1165, in up
  File "compose/cli/main.py", line 1161, in up
  File "compose/project.py", line 708, in up
  File "compose/parallel.py", line 106, in parallel_execute
  File "compose/parallel.py", line 204, in producer
  File "compose/project.py", line 694, in do
  File "compose/service.py", line 580, in execute_convergence_plan
  File "compose/service.py", line 502, in _execute_convergence_recreate
  File "compose/parallel.py", line 106, in parallel_execute
  File "compose/parallel.py", line 204, in producer
  File "compose/service.py", line 495, in recreate
  File "compose/service.py", line 614, in recreate_container
  File "compose/service.py", line 333, in create_container
  File "compose/service.py", line 918, in _get_container_create_options
  File "compose/service.py", line 958, in _build_container_volume_options
  File "compose/service.py", line 1552, in merge_volume_bindings
  File "compose/service.py", line 1582, in get_container_data_volumes
KeyError: 'ContainerConfig'
[9741] Failed to execute script docker-compose
user@VPN:~/standardnotes$
```

**Comment by ChesterHCopperpot** [comment]
Running the mysql -V command results in: `mysql  Ver 15.1 Distrib 10.3.39-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

**Comment by jelkose** [comment]
Could You share the contents of Your docker-compose file?
The output of mysql -V looks like You've got a very old version of MariaDB running. Did You execute Your command inside the db container or on Your machine?
