### ISSUE TITLE
Error occured while handling SQS message on fresh install

### ISSUE THREAD

**Issue by Stars-** [standardnotes/server#1067]
Server software will start up and splash will appear through web link. I am however not able to connect to the server through either the linux or android client. Viewing logs will spam variations of `Error occured while handling SQS message: SQSError: SQS receive message failed: The specified queue does not exist.` Not sure what is going on, I tried removing the application and doing a fresh install to no avail. 

[debug.txt](https://github.com/user-attachments/files/17949294/debug.txt)

**Comment by ksstormnet** [comment]
Having the same issue.

`
{"level":"error","message":"Error occured while handling SQS message: SQSError: SQS receive message failed: The specified queue does not exist.\n    at toSQSError (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/errors.js:47:22)\n    at Consumer.receiveMessage (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/consumer.js:189:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 'QueueDoesNotExist',\n  statusCode: 400,\n  retryable: undefined,\n  service: undefined,\n  fault: 'client',\n  time: 2024-12-23T05:14:34.870Z\n}","service":"auth:worker"}
{"level":"error","message":"Error occured while handling SQS message: SQSError: SQS receive message failed: The specified queue does not exist.\n    at toSQSError (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/errors.js:47:22)\n    at Consumer.receiveMessage (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/consumer.js:189:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 'QueueDoesNotExist',\n  statusCode: 400,\n  retryable: undefined,\n  service: undefined,\n  fault: 'client',\n  time: 2024-12-23T05:14:34.914Z\n}","service":"auth:worker"}
{"level":"error","message":"Error occured while handling SQS message: SQSError: SQS receive message failed: The specified queue does not exist.\n    at toSQSError (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/errors.js:47:22)\n    at Consumer.receiveMessage (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/consumer.js:189:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 'QueueDoesNotExist',\n  statusCode: 400,\n  retryable: undefined,\n  service: undefined,\n  fault: 'client',\n  time: 2024-12-23T05:14:34.957Z\n}","service":"auth:worker"}
{"level":"error","message":"Error occured while handling SQS message: SQSError: SQS receive message failed: The specified queue does not exist.\n    at toSQSError (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/errors.js:47:22)\n    at Consumer.receiveMessage (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/consumer.js:189:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 'QueueDoesNotExist',\n  statusCode: 400,\n  retryable: undefined,\n  service: undefined,\n  fault: 'client',\n  time: 2024-12-23T05:14:35.000Z\n}","service":"auth:worker"}
{"level":"error","message":"Error occured while handling SQS message: SQSError: SQS receive message failed: The specified queue does not exist.\n    at toSQSError (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/errors.js:47:22)\n    at Consumer.receiveMessage (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/consumer.js:189:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 'QueueDoesNotExist',\n  statusCode: 400,\n  retryable: undefined,\n  service: undefined,\n  fault: 'client',\n  time: 2024-12-23T05:14:35.044Z\n}","service":"auth:worker"}
{"level":"error","message":"Error occured while handling SQS message: SQSError: SQS receive message failed: The specified queue does not exist.\n    at toSQSError (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/errors.js:47:22)\n    at Consumer.receiveMessage (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/consumer.js:189:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 'QueueDoesNotExist',\n  statusCode: 400,\n  retryable: undefined,\n  service: undefined,\n  fault: 'client',\n  time: 2024-12-23T05:14:35.087Z\n}","service":"auth:worker"}
{"level":"error","message":"Error occured while handling SQS message: SQSError: SQS receive message failed: The specified queue does not exist.\n    at toSQSError (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/errors.js:47:22)\n    at Consumer.receiveMessage (/opt/server/.yarn/__virtual__/sqs-consumer-virtual-a292e446e4/0/cache/sqs-consumer-npm-8.1.0-acaed020b6-7fe1c17b9f.zip/node_modules/sqs-consumer/dist/consumer.js:189:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 'QueueDoesNotExist',\n  statusCode: 400,\n  retryable: undefined,\n  service: undefined,\n  fault: 'client',\n  time: 2024-12-23T05:14:35.130Z\n}","service":"auth:worker"}
`
