### ISSUE TITLE
Often getting error 500 / "Could not pass the request to underlying service"

### ISSUE THREAD

**Issue by vocux** [standardnotes/server#471]
Hello, I recently switchted from the self hosted legacy setup to this new server structure. When I was on the legacy service everything worked flawlessly, but with the new server setup (I appreciate the new architechture with fewer containers!) the synchronization seems to have the "hiccups". The basic sync functionality works somewhat, but I often get sync request errors. For example after logging in, the first sync request (when I change a note) always comes back with an error but any subsequent sync reqests go through. Then if I wait a while, the first request is an error again and any subsequent requests go through. So basically I can sync my notes, yes, but other functionalities like for example deleting a note or multiple notes or creating a note is barely possible. The action is so often interrupted by these unable to sync messages and sometimes get a ton of "conflicting" note copies due to the errors.
Never had any of these issues on the legacy setup. Any help is greatly appreciated!

These are error messages I could dig up:

App says
Failed to load resource: the server responded with a status of 500 ()

From api-gateway.log:
{"level":"error","message":"Could not pass the request to http://localhost:3101/items/sync on underlying service: {\"error\":{\"message\":\"Unfortunately, we couldn't handle your request. Please try again or contact our support if the error persists.\"}}"}

From all the worker logs (same message in auth-worker.log, files-worker.log, revisions-worker.log, syncing-server-worker.log):
{"level":"error","message":"Error occured while handling SQS message: SQSError: SQS receive message failed: getaddrinfo EAI_AGAIN localstack\n    at toSQSError (/opt/bundled/auth/.yarn/__virtual__/sqs-consumer-virtual-603a7c5831/0/cache/sqs-consumer-npm-6.2.1-857abd3d30-eba3c37353.zip/node_modules/sqs-consumer/dist/errors.js:40:22)\n    at Consumer.receiveMessage (/opt/bundled/auth/.yarn/__virtual__/sqs-consumer-virtual-603a7c5831/0/cache/sqs-consumer-npm-6.2.1-857abd3d30-eba3c37353.zip/node_modules/sqs-consumer/dist/consumer.js:149:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 'Error',\n  statusCode: undefined,\n  retryable: undefined,\n  service: undefined,\n  fault: undefined,\n  time: 2023-03-06T13:57:17.140Z\n}"}

**Comment by jackyzy823** [comment]
It looks like localstack not up or working properly. How about sharing your 1) docker-compose.yml and 2) logs  and state of localstack via `docker-compose logs localstack` / `docker-compose ps`
