### ISSUE TITLE
Cannot be used

### ISSUE THREAD

**Issue by eflydata** [standardnotes/server#504]
I have tested ubuntu 18.04, 22.04 versions and the following error occurs in all versions and does not sync and register.

{"level":"error","message":"Error occured while handling SQS message: SQSError: SQS receive message failed: The specified queue does not exist for this wsdl version.\n    at toSQSError (/opt/bundled/syncing-server/.yarn/__virtual__/sqs-consumer-virtual-603a7c5831/0/cache/sqs-consumer-npm-6.2.1-857abd3d30-eba3c37353.zip/node_modules/sqs-consumer/dist/errors.js:40:22)\n    at Consumer.receiveMessage (/opt/bundled/syncing-server/.yarn/__virtual__/sqs-consumer-virtual-603a7c5831/0/cache/sqs-consumer-npm-6.2.1-857abd3d30-eba3c37353.zip/node_modules/sqs-consumer/dist/consumer.js:149:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {\n  code: 'AWS.SimpleQueueService.NonExistentQueue',\n  statusCode: 400,\n  retryable: undefined,\n  service: undefined,\n  fault: 'client',\n  time: 2023-03-25T21:33:28.951Z\n}"}

**Comment by eflydata** [comment]
Some other errors include: New Relic 
Packaged docker does not need to test please remove: New Relic Optimization code.

**Comment by karolsojko** [comment]
New Relic is now disabled by default. Fixed by: https://github.com/standardnotes/server/commit/4ad1cccc33cb38f3531b9e1314f1c8535b451d49

The initial issue with SQS might be a duplicate of #471
