### ISSUE TITLE
Access denied problem with syncing-server and revisions after migrating to V2

### ISSUE THREAD

**Issue by xthursdayx** [standardnotes/server#507]
I followed the directions [here](https://standardnotes.com/help/self-hosting/legacy-migration) to migrate my existing self-hosted setup to V2, however when I check the logs, I see that the syncing-server and revisions keep exiting:
```
==> logs/supervisord.log <==
2023-03-30 18:49:37,793 INFO spawned: 'revisions' with pid 1721
2023-03-30 18:49:37,793 INFO success: syncing-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-30 18:49:38,802 INFO success: revisions entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-30 18:49:39,950 WARN exited: syncing-server (exit status 1; not expected)
2023-03-30 18:49:40,104 INFO spawned: 'syncing-server' with pid 1741
2023-03-30 18:49:40,118 WARN exited: revisions (exit status 1; not expected)
```

When I then check the error logs, I see that access is denied to the database user std_notes_user using the password that I set in my `.env` file:
```
==> logs/syncing-server.err <==
/opt/bundled/syncing-server/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/packets/packet.js:728
    const err = new Error(message);
                ^

Error: Access denied for user 'std_notes_user'@'172.21.0.4' (using password: YES)
    at Packet.asError (/opt/bundled/syncing-server/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/opt/bundled/syncing-server/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/opt/bundled/syncing-server/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:487:32)
    at PacketParser.onPacket (/opt/bundled/syncing-server/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:94:12)
    at PacketParser.executeStart (/opt/bundled/syncing-server/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/bundled/syncing-server/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  sqlMessage: "Access denied for user 'std_notes_user'@'172.21.0.4' (using password: YES)",
  sql: undefined
}

Node.js v18.15.0
db (172.21.0.3:3306) open
cache (172.21.0.2:6379) open

==> logs/revisions.err <==
/opt/bundled/revisions/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/packets/packet.js:728
    const err = new Error(message);
                ^

Error: Access denied for user 'std_notes_user'@'172.21.0.4' (using password: YES)
    at Packet.asError (/opt/bundled/revisions/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/opt/bundled/revisions/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/opt/bundled/revisions/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:487:32)
    at PacketParser.onPacket (/opt/bundled/revisions/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:94:12)
    at PacketParser.executeStart (/opt/bundled/revisions/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/bundled/revisions/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  sqlMessage: "Access denied for user 'std_notes_user'@'172.21.0.4' (using password: YES)",
  sql: undefined
}

Node.js v18.15.0
db (172.21.0.3:3306) open
cache (172.21.0.2:6379) open
```
The only thing I can think is that the access is being denied because my previous self-hosted server used a distinct `revisions database` with a unique username and password, as defined by the variables in my previous `.env` file:
```
# Revisions Database
REVISIONS_DB_HOST=revisions-db
REVISIONS_DB_PORT=3306
REVISIONS_DB_USERNAME=revisions
REVISIONS_DB_PASSWORD=******************
REVISIONS_DB_DATABASE=revisions
REVISIONS_DB_DEBUG_LEVEL=all # "all" | "query" | "schema" | "error" | "warn" | "info" | "log" | "migration"
REVISIONS_DB_MIGRATIONS_PATH=dist/migrations/*.js
```
The new self-hosted server `.env` does not seem to include these `revisions db` variables any more. 

Am I missing something? Is this while access is being denied to `std_notes_user` and why both `syncing-server` and `revisions` keep exiting?

**Comment by karolsojko** [comment]
Hi @xthursdayx the migration process merges both the dbs that were previously existing into one. So the access denied issue is unrelated to the fact.

One more thing that could affect this is that you first run the self-hosted setup which already created a database and you then changed the passwords and user in the env vars. This will not work because the database creation process happens only once per initial start of the self hosting setup. It is mentioned in the docs: 

```
Note that the steps below will only work if you are setting up the new V2 infrastructure from scratch. If you have previously created a V2 setup, the import files will be ignored, as the database has already been created and migrated.
```

Did you by any chance run the setup before the import procedure?

**Comment by xthursdayx** [comment]
Thanks for the reply @karolsojko 

I followed the migration instructions as they're written, so didn't run the v2 server set up before adding my database dump files. As the guide describes, I added my db files into the `data/import` directory and then started the server containers via ` docker compose up -d`. 

Just to make sure I didn't make a mistake, I just deleted the `sn-v2` directory and the server containers (cache_self_hosted, db_self_hosted, localstack_self_hosted, and server_self_hosted), redumped my databases from my original SN self-hosted server, added them to a new `sn-v2` `data/import` director and started the stack again. I'm having the same `Error: Access denied for user` problem.

**Comment by xthursdayx** [comment]
For reference this is what my new `.env` file contains:
```
######
# DB #
######

DB_HOST=db
DB_PORT=3306
DB_USERNAME=std_notes_user
DB_PASSWORD=****************************
DB_DATABASE=standard_notes_db

#########
# CACHE #
#########

REDIS_PORT=6379
REDIS_HOST=cache

########
# KEYS #
########

AUTH_JWT_SECRET=*********************************
AUTH_SERVER_ENCRYPTION_SERVER_KEY=*******************************************
VALET_TOKEN_SECRET=**************************

##########
# FILES  #
##########

PUBLIC_FILES_SERVER_URL=https://files.my.domain
```

**Comment by karolsojko** [comment]
Ah … does the password in .env match the one in docker-compose.yml ?
