### ISSUE TITLE
Cant Use auth "'emergency_access_invitations' already exists" error in auth

### ISSUE THREAD

**Issue by Gr3nDiz3r** [standardnotes/server#532]
this error make auth not to work 

'emergency_access_invitations' already exists   

at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9) {
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlState: '42S01',
  sqlMessage: "Table 'emergency_access_invitations' already exists",
  sql: 'CREATE TABLE `emergency_access_invitations` (`uuid` varchar(36) NOT NULL, `grantor_uuid` varchar(36) NOT NULL, `grantee_uuid` varchar(36) NOT NULL, `status` varchar(36) NOT NULL, `expires_at` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, PRIMARY KEY (`uuid`)) ENGINE=InnoDB'
}
Migration "emergencyAccessInvitations1680597887475" failed, error: Table 'emergency_access_invitations' already exists
query: ROLLBACK
localhost:3101 is up. Proceeding to startup.

**Comment by karolsojko** [comment]
Hmm seems like something was aborted mid-flight and your migration has not been marked as done. Is this a fresh setup or an update?

**Comment by Gr3nDiz3r** [comment]
Not a fresh setup this setup is old and always updated from many months the error is new just 2 days ago

**Comment by karolsojko** [comment]
can you try executing the line below on a running setup:

```
    docker compose exec db sh -c "MYSQL_PWD=\$MYSQL_ROOT_PASSWORD mysql \$MYSQL_DATABASE -e \
      'DROP TABLE emergency_access_invitations' \
    "
```

And see if that allowed the migration to push through?

**Comment by Gr3nDiz3r** [comment]
Same its drop the table and after this its show same message on the log ..

QueryFailedError: Table 'emergency_access_invitations' already exists
    at Query.onResult (/opt/bundled/auth/.yarn/__virtual__/typeorm-virtual-1bc789ec99/0/cache/typeorm-npm-0.3.10-4667857f33-749e1a6777.zip/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:158:37)
    at Query.execute (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:487:32)
    at PacketParser.onPacket (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:94:12)
    at PacketParser.executeStart (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9) {
  query: 'CREATE TABLE `emergency_access_invitations` (`uuid` varchar(36) NOT NULL, `grantor_uuid` varchar(36) NOT NULL, `grantee_uuid` varchar(36) NOT NULL, `status` varchar(36) NOT NULL, `expires_at` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, PRIMARY KEY (`uuid`)) ENGINE=InnoDB',
  parameters: undefined,
  driverError: Error: Table 'emergency_access_invitations' already exists
      at Packet.asError (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:487:32)
      at PacketParser.onPacket (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:94:12)
      at PacketParser.executeStart (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/opt/bundled/auth/.yarn/cache/mysql2-npm-3.0.1-ceda50bb4d-6bbee1ee05.zip/node_modules/mysql2/lib/connection.js:101:25)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9) {
    code: 'ER_TABLE_EXISTS_ERROR',
    errno: 1050,
    sqlState: '42S01',
    sqlMessage: "Table 'emergency_access_invitations' already exists",
    sql: 'CREATE TABLE `emergency_access_invitations` (`uuid` varchar(36) NOT NULL, `grantor_uuid` varchar(36) NOT NULL, `grantee_uuid` varchar(36) NOT NULL, `status` varchar(36) NOT NULL, `expires_at` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, PRIMARY KEY (`uuid`)) ENGINE=InnoDB'
  },
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlState: '42S01',
  sqlMessage: "Table 'emergency_access_invitations' already exists",
  sql: 'CREATE TABLE `emergency_access_invitations` (`uuid` varchar(36) NOT NULL, `grantor_uuid` varchar(36) NOT NULL, `grantee_uuid` varchar(36) NOT NULL, `status` varchar(36) NOT NULL, `expires_at` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, PRIMARY KEY (`uuid`)) ENGINE=InnoDB'
}

Node.js v18.15.0
localhost (127.0.0.1:3101) open

**Comment by Gr3nDiz3r** [comment]
also the "syncing-server.log"  file

show thats 

No migrations are pending


query: SELECT * FROM `sn_db`.`migrations` `migrations` ORDER BY `id` DESC
No migrations are pending
{"level":"info","message":"Server started on port 3101"}

**Comment by CybersShell** [comment]
I am getting this same error.

**Comment by karolsojko** [comment]
@Gr3nDiz3r hmm if you deleted the table then it should push through - are you able to list the `migrations` table and see what's the last entry?

@CybersShell did you try the drop table command?

**Comment by Gr3nDiz3r** [comment]
the last entry is 


92 | 1678340701766 | removeAuthenticatorNamesFromServer1678340701766

**Comment by karolsojko** [comment]
Hmm this is very odd, I just tried to reproduce the update version procedure and it went smooth. It should mark the migration as done once the table is created. 

Hmm as a workaround can you add an entry in the migrations table that would correspond to the following:
```
| id | timestamp | name |
| _your_next_id | 1680608399813 | emergencyAccessEmailRecipients1680608399813 |
 ```

**Comment by Gr3nDiz3r** [comment]
i did this 

| id | timestamp | name |
| _your_next_id | 1680608399813 | emergencyAccessEmailRecipients1680608399813 |

and same message come ..


    code: 'ER_TABLE_EXISTS_ERROR',
    errno: 1050,
    sqlState: '42S01',
    sqlMessage: "Table 'emergency_access_invitations' already exists",
    sql: 'CREATE TABLE `emergency_access_invitations` (`uuid` varchar(36) NOT NULL, `grantor_uuid` varchar(36) NOT NULL, `grantee_uuid` varchar(36) NOT NULL, `status` varchar(36) NOT NULL, `expires_at` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, PRIMARY KEY (`uuid`)) ENGINE=InnoDB'
  },
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlState: '42S01',
  sqlMessage: "Table 'emergency_access_invitations' already exists",
  sql: 'CREATE TABLE `emergency_access_invitations` (`uuid` varchar(36) NOT NULL, `grantor_uuid` varchar(36) NOT NULL, `grantee_uuid` varchar(36) NOT NULL, `status` varchar(36) NOT NULL, `expires_at` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, PRIMARY KEY (`uuid`)) ENGINE=InnoDB'
}

Node.js v18.15.0
localhost (127.0.0.1:3101) open

![1](https://user-images.githubusercontent.com/90205251/230646283-72816bc8-fd13-4996-b693-3c6ed0e4c35a.png)

**Comment by Gr3nDiz3r** [comment]
i solve it by add this to migrations

| id | timestamp | name |
| _your_next_id | 1680597887475| emergencyAccessInvitations1680597887475|

**Comment by CybersShell** [comment]
> 

I did. Same error.

 I reverted back to a stable version using an old image's hash.

How do I add the workaround to the migration table?

**Comment by Gr3nDiz3r** [comment]
i did using phpmyadmin

**Comment by karolsojko** [comment]
@CybersShell I think you can try something like this:

```
    docker compose exec db sh -c "MYSQL_PWD=\$MYSQL_ROOT_PASSWORD mysql \$MYSQL_DATABASE -e \
      'INSERT INTO migrations (timestamp, name) VALUES (1680597887475, \"emergencyAccessInvitations1680597887475\");' \
    "
```
