### ISSUE TITLE
[BUG] Environment variable DB_TYPE not set - Self hosted syncing-server fails to start

### ISSUE THREAD

**Issue by homberger** [standardnotes/server#615]
When updating the Docker containers today, the syncing-server could not be started because the environment variable `DB_TYPE` is not set.

The (undocumented?) environment variable `DB_TYPE` did not have to be set by the administrator until now. Apparently `mysql` was used as default value.

This has apparently changed in at least one place recently :
https://github.com/standardnotes/server/blob/f9183b4c623e16e4c6bd2ab1e77760b8eeabbcc3/packages/syncing-server/src/Bootstrap/DataSource.ts#LL10C60-L10C60

On a self hosted standalone server the environment variable `DB_TYPE` defaulted to `mysql`. It is not documented anywhere as far as I know.

Where do we have to set that variable?
Is `mysql` the correct value?

Error message:
```
{"log":"[Docker] Starting Web...\n","stream":"stdout","time":"2023-05-29T21:05:42.386538834Z"}
{"log":"/workspace/packages/syncing-server/dist/src/Bootstrap/Env.js:16\n","stream":"stderr","time":"2023-05-29T21:05:44.469639055Z"}
{"log":"            throw new Error(`Environment variable ${key} not set`);\n","stream":"stderr","time":"2023-05-29T21:05:44.469680423Z"}
{"log":"            ^\n","stream":"stderr","time":"2023-05-29T21:05:44.469685332Z"}
{"log":"\n","stream":"stderr","time":"2023-05-29T21:05:44.469688839Z"}
{"log":"Error: Environment variable DB_TYPE not set\n","stream":"stderr","time":"2023-05-29T21:05:44.469692365Z"}
{"log":"    at Env.get (/workspace/packages/syncing-server/dist/src/Bootstrap/Env.js:16:19)\n","stream":"stderr","time":"2023-05-29T21:05:44.469696323Z"}
{"log":"    at Object.\u003canonymous\u003e (/workspace/packages/syncing-server/dist/src/Bootstrap/DataSource.js:9:34)\n","stream":"stderr","time":"2023-05-29T21:05:44.469699979Z"}
{"log":"    at Module._compile (node:internal/modules/cjs/loader:1267:14)\n","stream":"stderr","time":"2023-05-29T21:05:44.469710388Z"}
{"log":"    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)\n","stream":"stderr","time":"2023-05-29T21:05:44.469714536Z"}
{"log":"    at require$$0.Module._extensions..js (/workspace/.pnp.cjs:10987:33)\n","stream":"stderr","time":"2023-05-29T21:05:44.469718914Z"}
{"log":"    at Module.load (node:internal/modules/cjs/loader:1125:32)\n","stream":"stderr","time":"2023-05-29T21:05:44.469722451Z"}
{"log":"    at require$$0.Module._load (/workspace/.pnp.cjs:10825:14)\n","stream":"stderr","time":"2023-05-29T21:05:44.469725667Z"}
{"log":"    at Module.require (node:internal/modules/cjs/loader:1149:19)\n","stream":"stderr","time":"2023-05-29T21:05:44.469728191Z"}
{"log":"    at require (node:internal/modules/helpers:121:18)\n","stream":"stderr","time":"2023-05-29T21:05:44.469730977Z"}
{"log":"    at Object.\u003canonymous\u003e (/workspace/packages/syncing-server/dist/src/Bootstrap/Container.js:8:22)\n","stream":"stderr","time":"2023-05-29T21:05:44.469733471Z"}
{"log":"\n","stream":"stderr","time":"2023-05-29T21:05:44.469736266Z"}
{"log":"Node.js v20.1.0\n","stream":"stderr","time":"2023-05-29T21:05:44.469739893Z"}
```

**Comment by karolsojko** [comment]
Is this self-hosting v1 or v2? If it's the first one please upgrade to v2, here's a guide on how to migrate: https://standardnotes.com/help/self-hosting/legacy-migration
