### ISSUE TITLE
`auth` service keeps restarting in fresh v2 self hosted setup

### ISSUE THREAD

**Issue by hood** [standardnotes/server#861]
No idea on how to debug this, so even pointing me to a direction to investgate this further would be helpful.

My `auth` service keeps restarting for some reason I can’t seem to be able to figure out:

![image](https://github.com/standardnotes/server/assets/56588510/b8fe2cfe-fd46-474a-a1db-65dfe1211f60)

**Comment by kolaente** [comment]
Also hitting this. I tried with a fresh database and the error does not happen there but I can't access the service either (connection refused, nothing in the logs)

**Comment by karolsojko** [comment]
Hi,

can you supply me with the contents of `head logs/auth*` and `tail logs/auth*` so that we can see what's going on in the logs

**Comment by kolaente** [comment]
This seems to be the problem:

```
==> /var/apps/standard-notes/logs/auth.log <==
localhost:3101 is up. Proceeding to startup.
query: SELECT VERSION() AS `version`
info: All classes found using provided glob pattern "/opt/server/packages/auth/dist/src/Bootstrap/../../migrations/mysql/*.js" : "/opt/server/packages/auth/dist/migrations/mysql/1606470249553-init_database.js,/opt/server/packages/auth/dist/migrations/mysql/1610015065194-add_revoked_sessions.js,/opt/server/packages/auth/dist/migrations/mysql/1610025371088-add_foreign_key_to_revoked_sessions.js,/opt/server/packages/auth/dist/migrations/mysql/1612191669523-add_roles_and_permissions.js,/opt/server/packages/auth/dist/migrations/mysql/1612255683992-add_roles_and_permissions_data.js,/opt/server/packages/auth/dist/migrations/mysql/1612433739754-add_more_roles_and_permissions.js,/opt/server/packages/auth/dist/migrations/mysql/1614678016791-add_user_settings.js,/opt/server/packages/auth/dist/migrations/mysql/1614771815912-add_encrypted_version.js,/opt/server/packages/auth/dist/migrations/mysql/1614775877590-add_encrypted_version_for_user.js,/opt/server/packages/auth/dist/migrations/mysql/1624434102642-update_roles_and_permissions.js,/opt/server/packages/auth/dist/migrations/mysql/1625164984414-change_setting_timestamps.js,/opt/server/packages/auth/dist/migrations/mysql/1625227894975-change_setting_value_size.js,/opt/server/packages/auth/dist/migrations/mysql/1625767770284-change_setting_value_to_nullable.js,/opt/server/packages/auth/dist/migrations/mysql/1625807999951-add_unique_setting_index.js,/opt/server/packages/auth/dist/migrations/mysql/1626268390207-remove_unique_setting_index.js,/opt/server/packages/auth/dist/migrations/mysql/1626689139110-add_user_subscriptions.js,/opt/server/packages/auth/dist/migrations/mysql/1626717016896-fix_subscription_foreign_key.js,/opt/server/packages/auth/dist/migrations/mysql/1627638504691-move_mfa_items_to_user_settings.js,/opt/server/packages/auth/dist/migrations/mysql/1629215600192-generate_user_server_key.js,/opt/server/packages/auth/dist/migrations/mysql/1629217630132-encrypt_encoded_mfa_settings.js,/opt/server/packages/auth/dist/migrations/mysql/1629223072059-flatten_mfa_setting_and_encrypt.js,/opt/server/packages/auth/dist/migrations/mysql/1629703896382-add_markdown_math.js,/opt/server/packages/auth/dist/migrations/mysql/1629705289178-add_sensitive_flag.js,/opt/server/packages/auth/dist/migrations/mysql/1629972294975-fix_basic_and_core_user.js,/opt/server/packages/auth/dist/migrations/mysql/1630661830850-fix_encryption_version_on_mfa_settings.js,/opt/server/packages/auth/dist/migrations/mysql/1630905831679-add-cancelled-flag.js,/opt/server/packages/auth/dist/migrations/mysql/1634064348750-add_offline_settings.js,/opt/server/packages/auth/dist/migrations/mysql/1634102065310-add_offline_subscriptions.js,/opt/server/packages/auth/dist/migrations/mysql/1634102764797-add_offline_user_roles.js,/opt/server/packages/auth/dist/migrations/mysql/1635167238332-remove_spreadsheets_from_plus_plan.js,/opt/server/packages/auth/dist/migrations/mysql/1635172524403-add_subscription_id.js,/opt/server/packages/auth/dist/migrations/mysql/1635344737460-add_missing_permissions.js,/opt/server/packages/auth/dist/migrations/mysql/1635860707639-add_mandatory_subscription_id.js,/opt/server/packages/auth/dist/migrations/mysql/1638388151083-add_tags_and_focus_permissions.js,/opt/server/packages/auth/dist/migrations/mysql/1639998097029-add_role_version.js,/opt/server/packages/auth/dist/migrations/mysql/1640701224273-add-smart-tags.js,/opt/server/packages/auth/dist/migrations/mysql/1640862425427-remove_no_distraction_theme.js,/opt/server/packages/auth/dist/migrations/mysql/1645094434931-add_sign_in_alerts_permission.js,/opt/server/packages/auth/dist/migrations/mysql/1646817642385-add_markdown_visual_editor_permissions.js,/opt/server/packages/auth/dist/migrations/mysql/1647253634773-fix_storage_quota_on_plans.js,/opt/server/packages/auth/dist/migrations/mysql/1647421277767-remove_user_agent.js,/opt/server/packages/auth/dist/migrations/mysql/1647862631224-add_readonly_sessions.js,/opt/server/packages/auth/dist/migrations/mysql/1648112718114-add_tag_nesting_permission.js,/opt/server/packages/auth/dist/migrations/mysql/1648458841415-add_shared_subscription_invitations.js,/opt/server/packages/auth/dist/migrations/mysql/1648550676786-add_subscription_types.js,/opt/server/packages/auth/dist/migrations/mysql/1648629732139-add_beta_files_user_role.js,/opt/server/packages/auth/dist/migrations/mysql/1649660400536-add_subscription_settings.js,/opt/server/packages/auth/dist/migrations/mysql/1649679945386-remove_files_settings_from_user_settings.js,/opt/server/packages/auth/dist/migrations/mysql/1650890853447-change_upload_quota_tiers.js,/opt/server/packages/auth/dist/migrations/mysql/1651046286472-add_2fa.js,/opt/server/packages/auth/dist/migrations/mysql/1651064332146-remove_2fa_manager.js,/opt/server/packages/auth/dist/migrations/mysql/1652258146238-add_missing_plus_permissions.js,/opt/server/packages/auth/dist/migrations/mysql/1652786070920-remove_basic_user_role.js,/opt/server/packages/auth/dist/migrations/mysql/1652880249670-add_analytics_entities.js,/opt/server/packages/auth/dist/migrations/mysql/1654760926952-add_email_backup_permission.js,/opt/server/packages/auth/dist/migrations/mysql/1654877423147-add_advanced_checklist_editor_permission.js,/opt/server/packages/auth/dist/migrations/mysql/1661771230400-revoked_session_data.js,/opt/server/packages/auth/dist/migrations/mysql/1663073954000-add_subcription_sharing_permission.js,/opt/server/packages/auth/dist/migrations/mysql/1663321030000-add_renewed_at_column.js,/opt/server/packages/auth/dist/migrations/mysql/1664971834974-groups.js,/opt/server/packages/auth/dist/migrations/mysql/1665047863774-remove-groups.js,/opt/server/packages/auth/dist/migrations/mysql/1667818539829-remove_analytics.js,/opt/server/packages/auth/dist/migrations/mysql/1671448907955-add_session_traces.js,/opt/server/packages/auth/dist/migrations/mysql/1671561748264-add_session_traces_compound_index.js,/opt/server/packages/auth/dist/migrations/mysql/1672223738686-add_authenticators.js,/opt/server/packages/auth/dist/migrations/mysql/1672227471677-add_authenticator_challenges.js,/opt/server/packages/auth/dist/migrations/mysql/1672232035280-fix_authenticator_data_types.js,/opt/server/packages/auth/dist/migrations/mysql/1672299743840-add_unique_index_on_challenges.js,/opt/server/packages/auth/dist/migrations/mysql/1672307975117-remove_compound_index.js,/opt/server/packages/auth/dist/migrations/mysql/1672317378817-add_authenticator_name.js,/opt/server/packages/auth/dist/migrations/mysql/1673951291148-add_super_editor.js,/opt/server/packages/auth/dist/migrations/mysql/1674739193816-fix-client-id-type-in-authenticators.js,/opt/server/packages/auth/dist/migrations/mysql/1678110075698-remove-sign-in-emails-on-free-acounts.js,/opt/server/packages/auth/dist/migrations/mysql/1678266947362-add-internal-team-user-role.js,/opt/server/packages/auth/dist/migrations/mysql/1678340701766-remove-authenticator-names-from-server.js,/opt/server/packages/auth/dist/migrations/mysql/1680597887475-emergency-access-invitations.js,/opt/server/packages/auth/dist/migrations/mysql/1681984540867-enable-u2f.js,/opt/server/packages/auth/dist/migrations/mysql/1682926032072-cache-entries.js,/opt/server/packages/auth/dist/migrations/mysql/1683017908845-change-cache-table-name.js,/opt/server/packages/auth/dist/migrations/mysql/1692348191367-add-transition-role.js,/opt/server/packages/auth/dist/migrations/mysql/1694000575425-add-shared-vault-users.js,/opt/server/packages/auth/dist/migrations/mysql/1694157482134-add_vaults_user.js,/opt/server/packages/auth/dist/migrations/mysql/1695283870612-add-designated-survivor.js,/opt/server/packages/auth/dist/migrations/mysql/1697704066569-remove-transition-role.js"
query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'standard_notes_db' AND `TABLE_NAME` = 'migrations'
query: SELECT * FROM `standard_notes_db`.`migrations` `migrations` ORDER BY `id` DESC
114 migrations are already loaded in the database.
84 migrations were found in the source code.
RemoveNotifications1695643525793 is the last executed migration. It was executed on Mon Sep 25 2023 12:05:25 GMT+0000 (Coordinated Universal Time).
9 migrations are new migrations must be executed.
query: START TRANSACTION
query: CREATE TABLE `emergency_access_invitations` (`uuid` varchar(36) NOT NULL, `grantor_uuid` varchar(36) NOT NULL, `grantee_uuid` varchar(36) NOT NULL, `status` varchar(36) NOT NULL, `expires_at` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, PRIMARY KEY (`uuid`)) ENGINE=InnoDB
query failed: CREATE TABLE `emergency_access_invitations` (`uuid` varchar(36) NOT NULL, `grantor_uuid` varchar(36) NOT NULL, `grantee_uuid` varchar(36) NOT NULL, `status` varchar(36) NOT NULL, `expires_at` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, PRIMARY KEY (`uuid`)) ENGINE=InnoDB
error: Error: Table 'emergency_access_invitations' already exists
query: ROLLBACK

**Comment by karolsojko** [comment]
hmm 🤔 can you manually delete the `emergency_access_invitations` in your db? It is not used for anything yet

**Comment by kolaente** [comment]
Then it fails with this error:

```
==> /var/apps/standard-notes/logs/auth.err <==
/opt/server/.yarn/__virtual__/typeorm-virtual-39f2df0bb4/0/cache/typeorm-npm-0.3.17-f8c2578e7f-3a7fe2a5e9.zip/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:158
                        return fail(new QueryFailedError_1.QueryFailedError(query, parameters, err));
                                    ^

QueryFailedError: Referencing column 'grantor_uuid' and referenced column 'uuid' in foreign key constraint 'grantor_uuid_fk' are incompatible.
    at Query.onResult (/opt/server/.yarn/__virtual__/typeorm-virtual-39f2df0bb4/0/cache/typeorm-npm-0.3.17-f8c2578e7f-3a7fe2a5e9.zip/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:158:37)
    at Query.execute (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/connection.js:490:32)
    at PacketParser.onPacket (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/connection.js:95:12)
    at PacketParser.executeStart (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/connection.js:102:25)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10) {
  query: 'ALTER TABLE `emergency_access_invitations` ADD CONSTRAINT `grantor_uuid_fk` FOREIGN KEY (`grantor_uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION',
  parameters: undefined,
  driverError: Error: Referencing column 'grantor_uuid' and referenced column 'uuid' in foreign key constraint 'grantor_uuid_fk' are incompatible.
      at Packet.asError (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/connection.js:490:32)
      at PacketParser.onPacket (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/connection.js:95:12)
      at PacketParser.executeStart (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/opt/server/.yarn/cache/mysql2-npm-3.3.3-d2fe8cf512-4bf7ace8f1.zip/node_modules/mysql2/lib/connection.js:102:25)
      at Socket.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:343:12)
      at readableAddChunk (node:internal/streams/readable:316:9)
      at Readable.push (node:internal/streams/readable:253:10) {
    code: 'ER_FK_INCOMPATIBLE_COLUMNS',
    errno: 3780,
    sqlState: 'HY000',
    sqlMessage: "Referencing column 'grantor_uuid' and referenced column 'uuid' in foreign key constraint 'grantor_uuid_fk' are incompatible.",
    sql: 'ALTER TABLE `emergency_access_invitations` ADD CONSTRAINT `grantor_uuid_fk` FOREIGN KEY (`grantor_uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION'
  },
  code: 'ER_FK_INCOMPATIBLE_COLUMNS',
  errno: 3780,
  sqlState: 'HY000',
  sqlMessage: "Referencing column 'grantor_uuid' and referenced column 'uuid' in foreign key constraint 'grantor_uuid_fk' are incompatible.",
  sql: 'ALTER TABLE `emergency_access_invitations` ADD CONSTRAINT `grantor_uuid_fk` FOREIGN KEY (`grantor_uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION'
}

Node.js v20.6.1
localhost (127.0.0.1:3101) open

**Comment by hood** [comment]
My issue in `auth.err` is:
```
Node.js v20.6.1
localhost (127.0.0.1:3101) open
/opt/server/packages/auth/dist/src/Domain/Encryption/CrypterNode.js:32
            throw Error('ENCRYPTION_SERVER_KEY must be a hex string exactly 32 bytes long!');
                  ^

Error: ENCRYPTION_SERVER_KEY must be a hex string exactly 32 bytes long!
    at new CrypterNode (/opt/server/packages/auth/dist/src/Domain/Encryption/CrypterNode.js:32:19)
    at createInstanceWithInjections (/opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/instantiation.js:119:20)
    at _createInstance (/opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/instantiation.js:109:22)
    at resolveInstance (/opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/instantiation.js:200:18)
    at _getResolvedFromBinding (/opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/resolver.js:109:58)
    at /opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/resolver.js:127:22
    at _resolveInScope (/opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/resolver.js:121:14)
    at _resolveBinding (/opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/resolver.js:126:12)
    at /opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/resolver.js:88:20
    at childRequests.reduce.constructorInjections (/opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/instantiation.js:85:25)
.js:126:12)
    at /opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/resolver.js:88:20
    at childRequests.reduce.constructorInjections (/opt/server/.yarn/cache/inversify-npm-6.0.1-39ef6784da-9563eaccdf.zip/node_modules/inversify/lib/resolution/instantiation.js:85:25)
```
